######################
#     ITEM NAMES     #
######################

# Bats, Item Code 0xxxx
default_bat = "Default Bat"
angel_bat = "Angel Bat"
fizzy_bat = "Fizzy Bat"
phant_bat = "Phant Bat"
power_bat = "Power Bat"
pink_bat = "Pink Bat"

# Collectable Items, Item Code 1xxxx
fizzy_ice_cream = "Fizzy Ice Cream"
phant = "Phant"
postcard_mola_town = "Mola Town Postcard"
postcard_belwheat_valley = "Belwheat Valley Postcard"
postcard_gc_warehouse = "GC Warehouse Postcard"
postcard_entrance_ruins = "Entrance Ruins Postcard"
postcard_gc_factory = "GC Factory Postcard"
postcard_forest_cavern = "Forest Cavern Postcard"
postcard_eroded_beach = "Eroded Beach Postcard"
postcard_port_naga = "Port Naga Postcard"
postcard_basin_21 = "Basin 21 Postcard"
postcard_pastel_strata = "Pastel Strata Postcard"
postcard_precipice_bridge = "Precipice Bridge Postcard"
postcard_villiths_drain = "Villith's Drain Postcard"
butter_card = "Butter's Contact Card"

# Equiptment, Item Code 2xxxx
logbook = "Logbook"
master_key = "Master Key"
train_ticket = "Train Ticket"
roller_blades = "Roller Blades"
baseball_cap = "Baseball Cap"
ball_power = "Ball Power"
wave_dash_power = "Wave Dash Power"

# Blocks in the world, Item Code 3xxxx
yellow_fence = "Yellow Fence"
jump_block = "Jump Block"
momentum_launcher = "Momentum Launcher"
vector_block = "Vector Block"
charge_block = "Charge Block"
super_jump_block = "Super Jump Block"
float_block = "Float Block"

# Filler Items, Item Code 4xxxx
nothing = "Nothing"

# Trap Items, Item Code 5xxxx
# TODO: add more
uppie_strike = "Uppie Strike"
creacher_jumpscare = "Creacher Jumpscare" # use the rare creacher fade in

######################
#    REGION NAMES    #
######################

mola_town = "Mola Town"
belwheat_valley = "Belwheat Valley"
gc_warehouse = "GC Warehouse"
entrance_ruins = "Entrance Ruins"
goldcherry_factory = "Goldcherry Factory"
cliff_face = "Cliff Face"
forest_cavern = "Forest Cavern"
eroded_beach = "Eroded Beach"
port_naga = "Port Naga"
basin_21 = "Basin 21"
pastel_strata = "Pastel Strata"
astral_tower = "Astral Tower"
precipice_bridge = "Precipice Bridge"
terminus = "Terminus"
heavens_channel = "Heaven's Channel"
jalta_dregs = "Jalta Dregs"
creacher_cave = "Creacher Cave"
terminal_station = "Terminal Station"
abandoned_district = "Abandoned District"
power_room = "Power Room"
villiths_drain = "Villith's Drain"
false_field = "False Field"
plateau_underside = "Plateau Underside"
satellite_ranch = "Satellite Ranch"
sand_hell = "Sand Hell"
warp_room = "Warp Room"
drain_room = "Drain Room"
ediface_roots = "Ediface Roots"
third_cistern = "Third Cistern"

######################
#   LOCATION NAMES   #
######################

## Fizzy Ice Cream Locations, Location Code 0xxxx ##
fizzy_mola_town_1 = "Fizzy - left of Mola Town"
fizzy_mola_town_2 = "Fizzy - on the climb to Jalta Dregs"
fizzy_belwheat_valley_1 = "Fizzy - hidden pit in Belwheat Valley"
fizzy_gc_warehouse_1 = "Fizzy - at the top of the GC Warehouse"
fizzy_entrance_ruins_1 = "Fizzy - above a checkpoint in the Entrance Ruins"
fizzy_entrance_ruins_2 = "Fizzy - platforming puzzle in the top left of the Entrance Ruins"
fizzy_gc_factory_1 = "Fizzy - lava tunnel in the GC Factory"
fizzy_gc_factory_2 = "Fizzy - island on the Cliff Face"
fizzy_forest_cavern_1 = "Fizzy - platforming puzzle in the top right of the Forest Cavern"
fizzy_eroded_beach_1 = "Fizzy - platforming puzzle at the end of the Eroded Beach"
fizzy_port_naga_1 = "Fizzy - platform above Observer in Port Naga"
fizzy_port_naga_2 = "Fizzy - isolated platform to the left of Port Naga"
fizzy_port_naga_3 = "Fizzy - baseball minigame in Port Naga"
fizzy_port_naga_4 = "Fizzy - jellon minigame in Port Naga"
fizzy_basin_21_1 = "Fizzy - at the entrance to the puzzle in the top of Basin 21"
fizzy_basin_21_2 = "Fizzy - at the end of the long platforming puzzle in Basin 21"
fizzy_pastel_strata_1 = "Fizzy - underneath the Phant room in Pastel Strata"
fizzy_precipice_bridge_1 = "Fizzy - puzzle in the middle of the Precipice Bridge"
fizzy_precipice_bridge_2 = "Fizzy - behind the glass at the end of the Precipice Bridge"
fizzy_villiths_drain_1 = "Fizzy - hidden room behind a checkpoint in Villith's Drain"

## Postcard Locations, Location Code 1xxxx ##
collect_postcard_mola_town = "Postcard - Mola Town"
collect_postcard_belwheat_valley = "Postcard - Belwheat Valley"
collect_postcard_gc_warehouse = "Postcard - GC Warehouse"
collect_postcard_entrance_ruins = "Postcard - Entrance Ruins"
collect_postcard_gc_factory = "Postcard - GC Factory"
collect_postcard_forest_cavern = "Postcard - Forest Cavern"
collect_postcard_eroded_beach = "Postcard - Eroded Beach"
collect_postcard_port_naga = "Postcard - Port Naga"
collect_postcard_basin_21 = "Postcard - Basin 21"
collect_postcard_pastel_strata = "Postcard - Pastel Strata"
collect_postcard_precipice_bridge = "Postcard - Precipice Bridge"
collect_postcard_villiths_drain = "Postcard - Villith's Drain"
collect_butter_card = "Postcard - Butter's Contact Card"

## Phant Locations, Location Code 2xxxx ##
phant_1 = "Phant - Cliff Face house"
phant_2 = "Phant - Eroded Beach puzzle"
phant_3 = "Phant - Basin 21 top puzzle"
phant_4 = "Phant - Basin 21 bottom puzzle"
phant_5 = "Phant - Pastel Strata island puzzle"
phant_6 = "Phant - Jalta Dregs warp zone outside"
phant_7 = "Phant - Jalta Dregs cliff backside"

## Key Item Locations, Location Code 3xxxx ##
collect_logbook = "Collect Item - Logbook"
collect_master_key = "Collect Item - Master Key"
collect_train_ticket = "Collect Item - Train Ticket"
collect_roller_blades = "Collect Item - Roller Blades"
collect_baseball_cap = "Collect Item - Baseball Cap"

## Bat Locations, Location Code 4xxxx ##
collect_default_bat = "Collect Item - Default Bat"
collect_angel_bat = "Collect Item - Angel Bat"
collect_fizzy_bat = "Collect Item - Fizzy Bat"
collect_phant_bat = "Collect Item - Phant Bat"
collect_power_bat = "Collect Item - Power Bat"
collect_pink_bat = "Collect Item - Pink Bat"

## Location Visits, Location Code 5xxxx ##
visit_mola_town = "Visit Location - Mola Town"
visit_belwheat_valley = "Visit Location - Belwheat Valley"
visit_gc_warehouse = "Visit Location - GC Warehouse"
visit_entrance_ruins = "Visit Location - Entrance Ruins"
visit_goldcherry_factory = "Visit Location - Goldcherry Factory"
visit_cliff_face = "Visit Location - Cliff Face"
visit_forest_cavern = "Visit Location - Forest Cavern"
visit_eroded_beach = "Visit Location - Eroded Beach"
visit_port_naga = "Visit Location - Port Naga"
visit_basin_21 = "Visit Location - Basin 21"
visit_pastel_strata = "Visit Location - Pastel Strata"
visit_astral_tower = "Visit Location - Astral Tower"
visit_precipice_bridge = "Visit Location - Precipice Bridge"
visit_terminus = "Visit Location - Terminus"
visit_heavens_channel = "Visit Location - Heaven's Channel"
visit_jalta_dregs = "Visit Location - Jalta Dregs"
visit_creacher_cave = "Visit Location - Creacher Cave"
visit_terminal_station = "Visit Location - Terminal Station"
visit_abandoned_district = "Visit Location - Abandoned District"
visit_power_room = "Visit Location - Power Room"
visit_villiths_drain = "Visit Location - Villith's Drain"
visit_false_field = "Visit Location - False Field"
visit_plateau_underside = "Visit Location - Plateau Underside"
visit_satellite_ranch = "Visit Location - Satellite Ranch"
visit_sand_hell = "Visit Location - Sand Hell"
visit_warp_room = "Visit Location - Warp Room"
visit_drain_room = "Visit Location - Drain Room"
visit_ediface_roots = "Visit Location - Ediface Roots"
visit_third_cistern = "Visit Location - Third Cistern"

## Checkpoint Locations, Location Code 6xxxx ##
checkpoint_0_mola_town = "Reached Checkpoint 0 - Mola Town"
checkpoint_1_mola_town = "Reached Checkpoint 1 - Mola Town (Lake Jalta)"
checkpoint_1_belwheat_valley = "Reached Checkpoint 1 - Belwheat Valley"
checkpoint_2_belwheat_valley = "Reached Checkpoint 2 - Belwheat Valley"
checkpoint_3_belwheat_valley = "Reached Checkpoint 3 - Belwheat Valley"
checkpoint_4_belwheat_valley = "Reached Checkpoint 4 - Belwheat Valley"
checkpoint_1_gc_warehouse = "Reached Checkpoint 1 - GC Warehouse"
checkpoint_2_gc_warehouse = "Reached Checkpoint 2 - GC Warehouse"
checkpoint_3_gc_warehouse = "Reached Checkpoint 3 - GC Warehouse"
checkpoint_4_gc_warehouse = "Reached Checkpoint 4 - GC Warehouse"
checkpoint_5_gc_warehouse = "Reached Checkpoint 5 - GC Warehouse"
checkpoint_6_gc_warehouse = "Reached Checkpoint 6 - GC Warehouse"
checkpoint_1_entrance_ruins = "Reached Checkpoint 1 - Entrance Ruins"
checkpoint_2_entrance_ruins = "Reached Checkpoint 2 - Entrance Ruins"
checkpoint_3_entrance_ruins = "Reached Checkpoint 3 - Entrance Ruins"
checkpoint_1_gc_factory = "Reached Checkpoint 1 - GC Factory"
checkpoint_2_gc_factory = "Reached Checkpoint 2 - GC Factory"
checkpoint_3_gc_factory = "Reached Checkpoint 3 - GC Factory"
checkpoint_4_gc_factory = "Reached Checkpoint 4 - GC Factory"
checkpoint_5_gc_factory = "Reached Checkpoint 5 - GC Factory"
checkpoint_6_gc_factory = "Reached Checkpoint 6 - GC Factory (Cliff Face)"
checkpoint_1_forest_cavern = "Reached Checkpoint 1 - Forest Cavern"
checkpoint_2_forest_cavern = "Reached Checkpoint 2 - Forest Cavern"
checkpoint_3_forest_cavern = "Reached Checkpoint 3 - Forest Cavern"
checkpoint_4_forest_cavern = "Reached Checkpoint 4 - Forest Cavern"
checkpoint_5_forest_cavern = "Reached Checkpoint 5 - Forest Cavern"
checkpoint_1_eroded_beach = "Reached Checkpoint 1 - Eroded Beach"
checkpoint_2_eroded_beach = "Reached Checkpoint 2 - Eroded Beach"
checkpoint_3_eroded_beach = "Reached Checkpoint 3 - Eroded Beach"
checkpoint_4_eroded_beach = "Reached Checkpoint 4 - Eroded Beach"
checkpoint_5_eroded_beach = "Reached Checkpoint 5 - Eroded Beach"
checkpoint_6_eroded_beach = "Reached Checkpoint 6 - Eroded Beach"
checkpoint_1_port_naga = "Reached Checkpoint 1 - Port Naga"
checkpoint_2_port_naga = "Reached Checkpoint 2 - Port Naga"
checkpoint_1_basin_21 = "Reached Checkpoint 1 - Basin 21"
checkpoint_2_basin_21 = "Reached Checkpoint 2 - Basin 21"
checkpoint_3_basin_21 = "Reached Checkpoint 3 - Basin 21"
checkpoint_4_basin_21 = "Reached Checkpoint 4 - Basin 21"
checkpoint_5_basin_21 = "Reached Checkpoint 5 - Basin 21"
checkpoint_6_basin_21 = "Reached Checkpoint 6 - Basin 21"
checkpoint_7_basin_21 = "Reached Checkpoint 7 - Basin 21"
checkpoint_1_pastel_strata = "Reached Checkpoint 1 - Pastel Strata"
checkpoint_2_pastel_strata = "Reached Checkpoint 2 - Pastel Strata"
checkpoint_3_pastel_strata = "Reached Checkpoint 3 - Pastel Strata"
checkpoint_4_pastel_strata = "Reached Checkpoint 4 - Pastel Strata"
checkpoint_5_pastel_strata = "Reached Checkpoint 5 - Pastel Strata"
checkpoint_6_pastel_strata = "Reached Checkpoint 6 - Pastel Strata"
checkpoint_7_pastel_strata = "Reached Checkpoint 7 - Pastel Strata"
checkpoint_8_pastel_strata = "Reached Checkpoint 8 - Pastel Strata"
checkpoint_9_pastel_strata = "Reached Checkpoint 9 - Pastel Strata"
checkpoint_1_precipice_bridge = "Reached Checkpoint 1 - Precipice Bridge"
checkpoint_2_precipice_bridge = "Reached Checkpoint 2 - Precipice Bridge"
checkpoint_3_precipice_bridge = "Reached Checkpoint 3 - Precipice Bridge"
checkpoint_4_precipice_bridge = "Reached Checkpoint 4 - Precipice Bridge"
checkpoint_5_precipice_bridge = "Reached Checkpoint 5 - Precipice Bridge"
checkpoint_6_precipice_bridge = "Reached Checkpoint 6 - Precipice Bridge"
checkpoint_7_precipice_bridge = "Reached Checkpoint 7 - Precipice Bridge"
checkpoint_8_precipice_bridge = "Reached Checkpoint 8 - Precipice Bridge"
checkpoint_9_precipice_bridge = "Reached Checkpoint 9 - Precipice Bridge"
checkpoint_1_terminus = "Reached Checkpoint 1 - Terminus"
checkpoint_2_terminus = "Reached Checkpoint 2 - Terminus"
checkpoint_1_villiths_drain = "Reached Checkpoint 1 - Villith's Drain"
checkpoint_2_villiths_drain = "Reached Checkpoint 2 - Villith's Drain"
checkpoint_3_villiths_drain = "Reached Checkpoint 3 - Villith's Drain"
checkpoint_4_villiths_drain = "Reached Checkpoint 4 - Villith's Drain"
checkpoint_5_villiths_drain = "Reached Checkpoint 5 - Villith's Drain"
checkpoint_6_villiths_drain = "Reached Checkpoint 6 - Villith's Drain"
checkpoint_7_villiths_drain = "Reached Checkpoint 7 - Villith's Drain"
checkpoint_8_villiths_drain = "Reached Checkpoint 8 - Villith's Drain"
checkpoint_9_villiths_drain = "Reached Checkpoint 9 - Villith's Drain"
checkpoint_10_villiths_drain = "Reached Checkpoint 10 - Villith's Drain"
checkpoint_0_plateau_underside = "Reached Checkpoint 0 - Plateau Underside"
checkpoint_0_ediface_roots = "Reached Checkpoint 0 - Ediface Roots"
checkpoint_1_ediface_roots = "Reached Checkpoint 1 - Ediface Roots"
checkpoint_2_ediface_roots = "Reached Checkpoint 2 - Ediface Roots"
checkpoint_3_ediface_roots = "Reached Checkpoint 3 - Ediface Roots"
checkpoint_4_ediface_roots = "Reached Checkpoint 4 - Ediface Roots"
checkpoint_5_ediface_roots = "Reached Checkpoint 5 - Ediface Roots"
checkpoint_6_ediface_roots = "Reached Checkpoint 6 - Ediface Roots"
checkpoint_7_ediface_roots = "Reached Checkpoint 7 - Ediface Roots"
checkpoint_8_ediface_roots = "Reached Checkpoint 8 - Ediface Roots"
checkpoint_9_ediface_roots = "Reached Checkpoint 9 - Ediface Roots (Third Cistern)"